# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [1,2,3.3],
    [4,5,6.6]
])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])

In [5]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (3, 2, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.dtype, a1.size, type(a1)

((3,), dtype('int64'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, type(a2)

((2, 3), dtype('float64'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, type(a3)

((3, 2, 3), dtype('int64'), 18, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_ints = np.random.randint(0,10,size=(7,2))
rand_ints

array([[8, 0],
       [8, 7],
       [2, 0],
       [5, 4],
       [4, 3],
       [1, 9],
       [7, 2]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_floats = np.random.random(size=(3,5))
rand_floats

array([[0.95283827, 0.41252493, 0.06341816, 0.76306278, 0.9805189 ],
       [0.1760818 , 0.53581067, 0.47390738, 0.80935723, 0.16606541],
       [0.48432295, 0.31160665, 0.92928736, 0.22049275, 0.58790273]])

In [28]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_ints = np.random.randint(0,10,size=(4,6))
rand_ints

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_ints = np.random.randint(0,10,size=(3,7))

# Find the unique numbers in the array you just created
rand_ints, np.unique(rand_ints)

(array([[3, 7, 6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8, 0, 8],
        [6, 8, 7, 0, 7, 7, 2]]),
 array([0, 1, 2, 3, 4, 6, 7, 8, 9]))

In [42]:
# Find the 0'th index of the latest array you created
rand_ints[0]

array([3, 7, 6, 8, 7, 4, 1])

In [43]:
# Get the first 2 rows of latest array you created
rand_ints[:2]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [53]:
# Get the first 2 values of the first 2 rows of the latest array
rand_ints.shape, rand_ints[:2,:2]

((3, 7),
 array([[3, 7],
        [4, 7]]))

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ri = np.random.randint(0,10,size=(3,5))
rones = np.ones(shape=(3,5))

In [57]:
# Add the two arrays together
ri + rones

array([[ 7.,  7.,  9., 10., 10.],
       [ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.]])

In [58]:
# Create another array of ones of shape (5, 3)
r_ones = np.ones(shape=(5,3))

In [59]:
# Try add the array of ones and the other most recent array together
rones + r_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [60]:
# Create another array of ones of shape (3, 5)
rand_ones = np.ones(shape=(3,5))

In [62]:
# Subtract the new array of ones from the other most recent array
rones - rand_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
# Multiply the ones array with the latest array
rones * rand_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
# Take the latest array to the power of 2 using '**'
ri, ri ** 2

(array([[6, 6, 8, 9, 9],
        [2, 6, 0, 3, 3],
        [4, 6, 6, 3, 6]]),
 array([[36, 36, 64, 81, 81],
        [ 4, 36,  0,  9,  9],
        [16, 36, 36,  9, 36]]))

In [70]:
# Do the same thing with np.square()
np.square(ri)

array([[36, 36, 64, 81, 81],
       [ 4, 36,  0,  9,  9],
       [16, 36, 36,  9, 36]])

In [71]:
# Find the mean of the latest array using np.mean()
np.mean(ri)

5.133333333333334

In [72]:
# Find the maximum of the latest array using np.max()
np.max(ri)

9

In [73]:
# Find the minimum of the latest array using np.min()
np.min(ri)

0

In [77]:
# Find the standard deviation of the latest array
np.std(ri), np.sqrt(np.var(ri))

(2.4997777679003566, 2.4997777679003566)

In [78]:
# Find the variance of the latest array
np.var(ri)

6.24888888888889

In [82]:
# Reshape the latest array to (3, 5, 1)
ri.shape, ri.reshape(3,5,1)

((3, 5),
 array([[[6],
         [6],
         [8],
         [9],
         [9]],
 
        [[2],
         [6],
         [0],
         [3],
         [3]],
 
        [[4],
         [6],
         [6],
         [3],
         [6]]]))

In [83]:
# Transpose the latest array
ri.T

array([[6, 2, 4],
       [6, 6, 6],
       [8, 0, 6],
       [9, 3, 3],
       [9, 3, 6]])

What does the transpose do?

In [85]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(10, size=(3,2))

In [87]:
# Perform a dot product on the two newest arrays you created
mat1.dot(mat2), np.dot(mat1, mat2)

(array([[100, 116],
        [ 64,  32],
        [ 95, 101]]),
 array([[100, 116],
        [ 64,  32],
        [ 95, 101]]))

In [88]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size=(4,3))
mat4 = np.random.randint(10,size=(4,3))

In [89]:
# Perform a dot product on the two newest arrays you created
mat3.dot(mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [91]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
mat3.T.dot(mat4), np.dot(mat3.T, mat4)

(array([[56, 28,  0],
        [42, 31, 49],
        [57, 40, 33]]),
 array([[56, 28,  0],
        [42, 31, 49],
        [57, 40, 33]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [123]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(42)
mat5 = np.random.randint(10, size=(4,2))
mat6 = np.random.randint(10, size=(4,2))

In [124]:
# Compare the two arrays with '>'
mat5 > mat6

array([[False, False],
       [ True, False],
       [False,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [125]:
# Compare the two arrays with '>='
mat5 >= mat6

array([[False, False],
       [ True, False],
       [False,  True],
       [False,  True]])

In [126]:
# Find which elements of the first array are greater than 7
mat5 > 7

array([[False, False],
       [False, False],
       [False,  True],
       [False, False]])

In [127]:
# Which parts of each array are equal? (try using '==')
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [128]:
# Sort one of the arrays you just created in ascending order
mat5, np.sort(mat5)

(array([[6, 3],
        [7, 4],
        [6, 9],
        [2, 6]]),
 array([[3, 6],
        [4, 7],
        [6, 9],
        [2, 6]]))

In [129]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat6)

array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])

In [133]:
# Find the index with the maximum value in one of the arrays you've created
mat5.argmax(), np.argmax(mat5), mat5

(5,
 5,
 array([[6, 3],
        [7, 4],
        [6, 9],
        [2, 6]]))

In [132]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat5), mat5

(6,
 array([[6, 3],
        [7, 4],
        [6, 9],
        [2, 6]]))

In [134]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat5, axis=1)

array([0, 0, 1, 1])

In [135]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(mat5, axis=0)

array([3, 0])

In [141]:
# Create an array of normally distributed random numbers
mat7 = np.random.randn(3,5)
mat7

array([[-0.58087813, -0.52516981, -0.57138017, -0.92408284, -2.61254901],
       [ 0.95036968,  0.81644508, -1.523876  , -0.42804606, -0.74240684],
       [-0.7033438 , -2.13962066, -0.62947496,  0.59772047,  2.55948803]])

In [143]:
# Create an array with 10 evenly spaced numbers between 1 and 100
mat8 = np.linspace(1,100, 10)
mat8

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.